- title: Stackstone
  class: stackstone
  image: /assets/img/category-ledgestone.jpg
  link: /products/stackstone.html

- title: Historical Limestone Flooring
  class: historical 
  image: /assets/img/category-historical.jpg
  link: /products/historical.html

- title: Thinline Laminates 
  class: slimeline 
  image: /assets/img/category-slimline.jpg
  link: /products/thinline.html

- title: Timberline Wood Panels 
  class: timberline 
  image: /assets/img/category-timberline.jpg
  link: /products/timberline.html